// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.28.3
// source: study.proto

package study_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_study_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{0}
}

func (x *Image) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *Image) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Image) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type StudyInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StudyId             []byte                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	StudyName           *string                `protobuf:"bytes,2,opt,name=study_name,json=studyName,proto3,oneof" json:"study_name,omitempty"`
	Status              string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	OwnerId             []byte                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ImageUrl            *string                `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3,oneof" json:"image_url,omitempty"`
	PredictedClass      *string                `protobuf:"bytes,6,opt,name=predicted_class,json=predictedClass,proto3,oneof" json:"predicted_class,omitempty"`
	PredictedClassScore *float32               `protobuf:"fixed32,7,opt,name=predicted_class_score,json=predictedClassScore,proto3,oneof" json:"predicted_class_score,omitempty"`
	ErrorDescription    *string                `protobuf:"bytes,8,opt,name=error_description,json=errorDescription,proto3,oneof" json:"error_description,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StudyInfo) Reset() {
	*x = StudyInfo{}
	mi := &file_study_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudyInfo) ProtoMessage() {}

func (x *StudyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudyInfo.ProtoReflect.Descriptor instead.
func (*StudyInfo) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{1}
}

func (x *StudyInfo) GetStudyId() []byte {
	if x != nil {
		return x.StudyId
	}
	return nil
}

func (x *StudyInfo) GetStudyName() string {
	if x != nil && x.StudyName != nil {
		return *x.StudyName
	}
	return ""
}

func (x *StudyInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StudyInfo) GetOwnerId() []byte {
	if x != nil {
		return x.OwnerId
	}
	return nil
}

func (x *StudyInfo) GetImageUrl() string {
	if x != nil && x.ImageUrl != nil {
		return *x.ImageUrl
	}
	return ""
}

func (x *StudyInfo) GetPredictedClass() string {
	if x != nil && x.PredictedClass != nil {
		return *x.PredictedClass
	}
	return ""
}

func (x *StudyInfo) GetPredictedClassScore() float32 {
	if x != nil && x.PredictedClassScore != nil {
		return *x.PredictedClassScore
	}
	return 0
}

func (x *StudyInfo) GetErrorDescription() string {
	if x != nil && x.ErrorDescription != nil {
		return *x.ErrorDescription
	}
	return ""
}

func (x *StudyInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StudyInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateStudyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *Image                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	UserId        []byte                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudyRequest) Reset() {
	*x = CreateStudyRequest{}
	mi := &file_study_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudyRequest) ProtoMessage() {}

func (x *CreateStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudyRequest.ProtoReflect.Descriptor instead.
func (*CreateStudyRequest) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStudyRequest) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *CreateStudyRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

type CreateStudyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudyId       []byte                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStudyResponse) Reset() {
	*x = CreateStudyResponse{}
	mi := &file_study_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStudyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStudyResponse) ProtoMessage() {}

func (x *CreateStudyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStudyResponse.ProtoReflect.Descriptor instead.
func (*CreateStudyResponse) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{3}
}

func (x *CreateStudyResponse) GetStudyId() []byte {
	if x != nil {
		return x.StudyId
	}
	return nil
}

type GetStudyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudyId       []byte                 `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudyRequest) Reset() {
	*x = GetStudyRequest{}
	mi := &file_study_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudyRequest) ProtoMessage() {}

func (x *GetStudyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudyRequest.ProtoReflect.Descriptor instead.
func (*GetStudyRequest) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{4}
}

func (x *GetStudyRequest) GetStudyId() []byte {
	if x != nil {
		return x.StudyId
	}
	return nil
}

type GetStudyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Study         *StudyInfo             `protobuf:"bytes,1,opt,name=study,proto3" json:"study,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudyResponse) Reset() {
	*x = GetStudyResponse{}
	mi := &file_study_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudyResponse) ProtoMessage() {}

func (x *GetStudyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudyResponse.ProtoReflect.Descriptor instead.
func (*GetStudyResponse) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{5}
}

func (x *GetStudyResponse) GetStudy() *StudyInfo {
	if x != nil {
		return x.Study
	}
	return nil
}

type UpdateStudyInfoRequest struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	StudyId             []byte                  `protobuf:"bytes,1,opt,name=study_id,json=studyId,proto3" json:"study_id,omitempty"`
	StudyName           *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=study_name,json=studyName,proto3" json:"study_name,omitempty"`
	PredictedClass      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=predicted_class,json=predictedClass,proto3" json:"predicted_class,omitempty"`
	PredictedClassScore *wrapperspb.FloatValue  `protobuf:"bytes,4,opt,name=predicted_class_score,json=predictedClassScore,proto3" json:"predicted_class_score,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateStudyInfoRequest) Reset() {
	*x = UpdateStudyInfoRequest{}
	mi := &file_study_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudyInfoRequest) ProtoMessage() {}

func (x *UpdateStudyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudyInfoRequest.ProtoReflect.Descriptor instead.
func (*UpdateStudyInfoRequest) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateStudyInfoRequest) GetStudyId() []byte {
	if x != nil {
		return x.StudyId
	}
	return nil
}

func (x *UpdateStudyInfoRequest) GetStudyName() *wrapperspb.StringValue {
	if x != nil {
		return x.StudyName
	}
	return nil
}

func (x *UpdateStudyInfoRequest) GetPredictedClass() *wrapperspb.StringValue {
	if x != nil {
		return x.PredictedClass
	}
	return nil
}

func (x *UpdateStudyInfoRequest) GetPredictedClassScore() *wrapperspb.FloatValue {
	if x != nil {
		return x.PredictedClassScore
	}
	return nil
}

type UpdateStudyInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Study         *StudyInfo             `protobuf:"bytes,1,opt,name=study,proto3" json:"study,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStudyInfoResponse) Reset() {
	*x = UpdateStudyInfoResponse{}
	mi := &file_study_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStudyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStudyInfoResponse) ProtoMessage() {}

func (x *UpdateStudyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStudyInfoResponse.ProtoReflect.Descriptor instead.
func (*UpdateStudyInfoResponse) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStudyInfoResponse) GetStudy() *StudyInfo {
	if x != nil {
		return x.Study
	}
	return nil
}

type ListStudiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterStudyId []byte                 `protobuf:"bytes,1,opt,name=filter_study_id,json=filterStudyId,proto3" json:"filter_study_id,omitempty"`
	FilterUserId  []byte                 `protobuf:"bytes,2,opt,name=filter_user_id,json=filterUserId,proto3" json:"filter_user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudiesRequest) Reset() {
	*x = ListStudiesRequest{}
	mi := &file_study_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudiesRequest) ProtoMessage() {}

func (x *ListStudiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudiesRequest.ProtoReflect.Descriptor instead.
func (*ListStudiesRequest) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{8}
}

func (x *ListStudiesRequest) GetFilterStudyId() []byte {
	if x != nil {
		return x.FilterStudyId
	}
	return nil
}

func (x *ListStudiesRequest) GetFilterUserId() []byte {
	if x != nil {
		return x.FilterUserId
	}
	return nil
}

func (x *ListStudiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListStudiesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListStudiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Studies       []*StudyInfo           `protobuf:"bytes,1,rep,name=studies,proto3" json:"studies,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStudiesResponse) Reset() {
	*x = ListStudiesResponse{}
	mi := &file_study_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStudiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStudiesResponse) ProtoMessage() {}

func (x *ListStudiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_study_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStudiesResponse.ProtoReflect.Descriptor instead.
func (*ListStudiesResponse) Descriptor() ([]byte, []int) {
	return file_study_proto_rawDescGZIP(), []int{9}
}

func (x *ListStudiesResponse) GetStudies() []*StudyInfo {
	if x != nil {
		return x.Studies
	}
	return nil
}

func (x *ListStudiesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_study_proto protoreflect.FileDescriptor

const file_study_proto_rawDesc = "" +
	"\n" +
	"\vstudy.proto\x12\bstudy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"`\n" +
	"\x05Image\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"\x8f\x04\n" +
	"\tStudyInfo\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\fR\astudyId\x12\"\n" +
	"\n" +
	"study_name\x18\x02 \x01(\tH\x00R\tstudyName\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\fR\aownerId\x12 \n" +
	"\timage_url\x18\x05 \x01(\tH\x01R\bimageUrl\x88\x01\x01\x12,\n" +
	"\x0fpredicted_class\x18\x06 \x01(\tH\x02R\x0epredictedClass\x88\x01\x01\x127\n" +
	"\x15predicted_class_score\x18\a \x01(\x02H\x03R\x13predictedClassScore\x88\x01\x01\x120\n" +
	"\x11error_description\x18\b \x01(\tH\x04R\x10errorDescription\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\r\n" +
	"\v_study_nameB\f\n" +
	"\n" +
	"_image_urlB\x12\n" +
	"\x10_predicted_classB\x18\n" +
	"\x16_predicted_class_scoreB\x14\n" +
	"\x12_error_description\"T\n" +
	"\x12CreateStudyRequest\x12%\n" +
	"\x05image\x18\x01 \x01(\v2\x0f.study.v1.ImageR\x05image\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\fR\x06userId\"0\n" +
	"\x13CreateStudyResponse\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\fR\astudyId\",\n" +
	"\x0fGetStudyRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\fR\astudyId\"=\n" +
	"\x10GetStudyResponse\x12)\n" +
	"\x05study\x18\x01 \x01(\v2\x13.study.v1.StudyInfoR\x05study\"\x88\x02\n" +
	"\x16UpdateStudyInfoRequest\x12\x19\n" +
	"\bstudy_id\x18\x01 \x01(\fR\astudyId\x12;\n" +
	"\n" +
	"study_name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\tstudyName\x12E\n" +
	"\x0fpredicted_class\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x0epredictedClass\x12O\n" +
	"\x15predicted_class_score\x18\x04 \x01(\v2\x1b.google.protobuf.FloatValueR\x13predictedClassScore\"D\n" +
	"\x17UpdateStudyInfoResponse\x12)\n" +
	"\x05study\x18\x01 \x01(\v2\x13.study.v1.StudyInfoR\x05study\"\x90\x01\n" +
	"\x12ListStudiesRequest\x12&\n" +
	"\x0ffilter_study_id\x18\x01 \x01(\fR\rfilterStudyId\x12$\n" +
	"\x0efilter_user_id\x18\x02 \x01(\fR\ffilterUserId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"e\n" +
	"\x13ListStudiesResponse\x12-\n" +
	"\astudies\x18\x01 \x03(\v2\x13.study.v1.StudyInfoR\astudies\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount2\xc1\x02\n" +
	"\fStudyService\x12J\n" +
	"\vCreateStudy\x12\x1c.study.v1.CreateStudyRequest\x1a\x1d.study.v1.CreateStudyResponse\x12A\n" +
	"\bGetStudy\x12\x19.study.v1.GetStudyRequest\x1a\x1a.study.v1.GetStudyResponse\x12V\n" +
	"\x0fUpdateStudyInfo\x12 .study.v1.UpdateStudyInfoRequest\x1a!.study.v1.UpdateStudyInfoResponse\x12J\n" +
	"\vListStudies\x12\x1c.study.v1.ListStudiesRequest\x1a\x1d.study.v1.ListStudiesResponseBCZAgithub.com/imgrigorev/agrolab/study-service/pkg/study_v1;study_v1b\x06proto3"

var (
	file_study_proto_rawDescOnce sync.Once
	file_study_proto_rawDescData []byte
)

func file_study_proto_rawDescGZIP() []byte {
	file_study_proto_rawDescOnce.Do(func() {
		file_study_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_study_proto_rawDesc), len(file_study_proto_rawDesc)))
	})
	return file_study_proto_rawDescData
}

var file_study_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_study_proto_goTypes = []any{
	(*Image)(nil),                   // 0: study.v1.Image
	(*StudyInfo)(nil),               // 1: study.v1.StudyInfo
	(*CreateStudyRequest)(nil),      // 2: study.v1.CreateStudyRequest
	(*CreateStudyResponse)(nil),     // 3: study.v1.CreateStudyResponse
	(*GetStudyRequest)(nil),         // 4: study.v1.GetStudyRequest
	(*GetStudyResponse)(nil),        // 5: study.v1.GetStudyResponse
	(*UpdateStudyInfoRequest)(nil),  // 6: study.v1.UpdateStudyInfoRequest
	(*UpdateStudyInfoResponse)(nil), // 7: study.v1.UpdateStudyInfoResponse
	(*ListStudiesRequest)(nil),      // 8: study.v1.ListStudiesRequest
	(*ListStudiesResponse)(nil),     // 9: study.v1.ListStudiesResponse
	(*timestamppb.Timestamp)(nil),   // 10: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),  // 11: google.protobuf.StringValue
	(*wrapperspb.FloatValue)(nil),   // 12: google.protobuf.FloatValue
}
var file_study_proto_depIdxs = []int32{
	10, // 0: study.v1.StudyInfo.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: study.v1.StudyInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: study.v1.CreateStudyRequest.image:type_name -> study.v1.Image
	1,  // 3: study.v1.GetStudyResponse.study:type_name -> study.v1.StudyInfo
	11, // 4: study.v1.UpdateStudyInfoRequest.study_name:type_name -> google.protobuf.StringValue
	11, // 5: study.v1.UpdateStudyInfoRequest.predicted_class:type_name -> google.protobuf.StringValue
	12, // 6: study.v1.UpdateStudyInfoRequest.predicted_class_score:type_name -> google.protobuf.FloatValue
	1,  // 7: study.v1.UpdateStudyInfoResponse.study:type_name -> study.v1.StudyInfo
	1,  // 8: study.v1.ListStudiesResponse.studies:type_name -> study.v1.StudyInfo
	2,  // 9: study.v1.StudyService.CreateStudy:input_type -> study.v1.CreateStudyRequest
	4,  // 10: study.v1.StudyService.GetStudy:input_type -> study.v1.GetStudyRequest
	6,  // 11: study.v1.StudyService.UpdateStudyInfo:input_type -> study.v1.UpdateStudyInfoRequest
	8,  // 12: study.v1.StudyService.ListStudies:input_type -> study.v1.ListStudiesRequest
	3,  // 13: study.v1.StudyService.CreateStudy:output_type -> study.v1.CreateStudyResponse
	5,  // 14: study.v1.StudyService.GetStudy:output_type -> study.v1.GetStudyResponse
	7,  // 15: study.v1.StudyService.UpdateStudyInfo:output_type -> study.v1.UpdateStudyInfoResponse
	9,  // 16: study.v1.StudyService.ListStudies:output_type -> study.v1.ListStudiesResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_study_proto_init() }
func file_study_proto_init() {
	if File_study_proto != nil {
		return
	}
	file_study_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_study_proto_rawDesc), len(file_study_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_study_proto_goTypes,
		DependencyIndexes: file_study_proto_depIdxs,
		MessageInfos:      file_study_proto_msgTypes,
	}.Build()
	File_study_proto = out.File
	file_study_proto_goTypes = nil
	file_study_proto_depIdxs = nil
}
